### PR TITLE
Rails new on this bitch

### PR DESCRIPTION
**Pull request by swatkns785**

### CODE REVIEW

**Comment by nickcluc** [comment]
WE NEED TO DO CODE REVIEWS. WE HAVE RULES.

**Comment by swatkns785** [comment]
Do we need a code review for rails new, capybara, and rspec configs? If so, I quit.

**Comment by nickcluc** [comment]
I was joking. Jeeeez.

**Comment by swatkns785** [comment]
I know. Also, every branch and/or commit must have a swear. YEA BIATCH!

**Comment by nickcluc** [comment]
Great rule.

**Pull request merged**
